export const SEARCH_PLACE = 'SEARCH_PLACE';
export const SEARCH_PLACE_SUCCESS = 'SEARCH_PLACE_SUCCESS';
export const SEARCH_PLACE_FAILED = 'SEARCH_PLACE_FAILED';

export const GET_HISTORY = 'GET_HISTORY';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAILED = 'GET_HISTORY_FAILED';

export const SAVE_HISTORY = 'SAVE_HISTORY';
export const SAVE_HISTORY_SUCCESS = 'SAVE_HISTORY_SUCCESS';
export const SAVE_HISTORY_FAILED = 'SAVE_HISTORY_FAILED';
